import type { Metadata } from 'next'
import React from 'react'
import GlobalState from '@/app/_provider/GlobalState'
import './reset.css'
import './global.css'
import { DarkMode } from '@/app/_provider/darkmode'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<DarkMode />
			</head>
			<body>
				<GlobalState>{children}</GlobalState>
			</body>
		</html>
	)
}
